services:
  db:
    image: postgres:15-alpine
    container_name: vacancy_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Test"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: vacancy_rabbitmq
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: . 
      dockerfile: JobVacancyCollector/Dockerfile 
    container_name: vacancy_api
    depends_on:
      db: { condition: service_healthy }
      rabbitmq: { condition: service_healthy }
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=Test;Username=postgres;Password=admin
      - RabbitMq__Host=rabbitmq
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
      
  worker:
    build:
      context: . 
      dockerfile: JobVacancyCollector.Worker/Dockerfile 
    container_name: vacancy_worker
    depends_on:
      db: { condition: service_healthy }
      rabbitmq: { condition: service_healthy }
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=Test;Username=postgres;Password=admin
      - RabbitMq__Host=rabbitmq

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin 
    ports:
      - "5050:80"